# permissions for end users to edit clusterscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: basic-controller
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-editor-role
rules:
- apiGroups:
  - security.basiccontroller.com
  resources:
  - clusterscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.basiccontroller.com
  resources:
  - clusterscans/status
  verbs:
  - get
