apiVersion: security.basiccontroller.com/v1alpha1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: basic-controller
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  # TODO(user): Add fields here
